# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/tetsuo/src/code-master/Chapter5_NumberPlateRecognition

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/tetsuo/src/code-master/Chapter5_NumberPlateRecognition

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/local/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/tetsuo/src/code-master/Chapter5_NumberPlateRecognition/CMakeFiles /home/tetsuo/src/code-master/Chapter5_NumberPlateRecognition/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/tetsuo/src/code-master/Chapter5_NumberPlateRecognition/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ANPR

# Build rule for target.
ANPR: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ANPR
.PHONY : ANPR

# fast build rule for target.
ANPR/fast:
	$(MAKE) -f CMakeFiles/ANPR.dir/build.make CMakeFiles/ANPR.dir/build
.PHONY : ANPR/fast

#=============================================================================
# Target rules for targets named evalOCR

# Build rule for target.
evalOCR: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 evalOCR
.PHONY : evalOCR

# fast build rule for target.
evalOCR/fast:
	$(MAKE) -f CMakeFiles/evalOCR.dir/build.make CMakeFiles/evalOCR.dir/build
.PHONY : evalOCR/fast

#=============================================================================
# Target rules for targets named trainOCR

# Build rule for target.
trainOCR: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 trainOCR
.PHONY : trainOCR

# fast build rule for target.
trainOCR/fast:
	$(MAKE) -f CMakeFiles/trainOCR.dir/build.make CMakeFiles/trainOCR.dir/build
.PHONY : trainOCR/fast

#=============================================================================
# Target rules for targets named trainSVM

# Build rule for target.
trainSVM: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 trainSVM
.PHONY : trainSVM

# fast build rule for target.
trainSVM/fast:
	$(MAKE) -f CMakeFiles/trainSVM.dir/build.make CMakeFiles/trainSVM.dir/build
.PHONY : trainSVM/fast

DetectRegions.o: DetectRegions.cpp.o
.PHONY : DetectRegions.o

# target to build an object file
DetectRegions.cpp.o:
	$(MAKE) -f CMakeFiles/ANPR.dir/build.make CMakeFiles/ANPR.dir/DetectRegions.cpp.o
.PHONY : DetectRegions.cpp.o

DetectRegions.i: DetectRegions.cpp.i
.PHONY : DetectRegions.i

# target to preprocess a source file
DetectRegions.cpp.i:
	$(MAKE) -f CMakeFiles/ANPR.dir/build.make CMakeFiles/ANPR.dir/DetectRegions.cpp.i
.PHONY : DetectRegions.cpp.i

DetectRegions.s: DetectRegions.cpp.s
.PHONY : DetectRegions.s

# target to generate assembly for a file
DetectRegions.cpp.s:
	$(MAKE) -f CMakeFiles/ANPR.dir/build.make CMakeFiles/ANPR.dir/DetectRegions.cpp.s
.PHONY : DetectRegions.cpp.s

OCR.o: OCR.cpp.o
.PHONY : OCR.o

# target to build an object file
OCR.cpp.o:
	$(MAKE) -f CMakeFiles/ANPR.dir/build.make CMakeFiles/ANPR.dir/OCR.cpp.o
	$(MAKE) -f CMakeFiles/evalOCR.dir/build.make CMakeFiles/evalOCR.dir/OCR.cpp.o
	$(MAKE) -f CMakeFiles/trainOCR.dir/build.make CMakeFiles/trainOCR.dir/OCR.cpp.o
.PHONY : OCR.cpp.o

OCR.i: OCR.cpp.i
.PHONY : OCR.i

# target to preprocess a source file
OCR.cpp.i:
	$(MAKE) -f CMakeFiles/ANPR.dir/build.make CMakeFiles/ANPR.dir/OCR.cpp.i
	$(MAKE) -f CMakeFiles/evalOCR.dir/build.make CMakeFiles/evalOCR.dir/OCR.cpp.i
	$(MAKE) -f CMakeFiles/trainOCR.dir/build.make CMakeFiles/trainOCR.dir/OCR.cpp.i
.PHONY : OCR.cpp.i

OCR.s: OCR.cpp.s
.PHONY : OCR.s

# target to generate assembly for a file
OCR.cpp.s:
	$(MAKE) -f CMakeFiles/ANPR.dir/build.make CMakeFiles/ANPR.dir/OCR.cpp.s
	$(MAKE) -f CMakeFiles/evalOCR.dir/build.make CMakeFiles/evalOCR.dir/OCR.cpp.s
	$(MAKE) -f CMakeFiles/trainOCR.dir/build.make CMakeFiles/trainOCR.dir/OCR.cpp.s
.PHONY : OCR.cpp.s

Plate.o: Plate.cpp.o
.PHONY : Plate.o

# target to build an object file
Plate.cpp.o:
	$(MAKE) -f CMakeFiles/ANPR.dir/build.make CMakeFiles/ANPR.dir/Plate.cpp.o
.PHONY : Plate.cpp.o

Plate.i: Plate.cpp.i
.PHONY : Plate.i

# target to preprocess a source file
Plate.cpp.i:
	$(MAKE) -f CMakeFiles/ANPR.dir/build.make CMakeFiles/ANPR.dir/Plate.cpp.i
.PHONY : Plate.cpp.i

Plate.s: Plate.cpp.s
.PHONY : Plate.s

# target to generate assembly for a file
Plate.cpp.s:
	$(MAKE) -f CMakeFiles/ANPR.dir/build.make CMakeFiles/ANPR.dir/Plate.cpp.s
.PHONY : Plate.cpp.s

evalOCR.o: evalOCR.cpp.o
.PHONY : evalOCR.o

# target to build an object file
evalOCR.cpp.o:
	$(MAKE) -f CMakeFiles/evalOCR.dir/build.make CMakeFiles/evalOCR.dir/evalOCR.cpp.o
.PHONY : evalOCR.cpp.o

evalOCR.i: evalOCR.cpp.i
.PHONY : evalOCR.i

# target to preprocess a source file
evalOCR.cpp.i:
	$(MAKE) -f CMakeFiles/evalOCR.dir/build.make CMakeFiles/evalOCR.dir/evalOCR.cpp.i
.PHONY : evalOCR.cpp.i

evalOCR.s: evalOCR.cpp.s
.PHONY : evalOCR.s

# target to generate assembly for a file
evalOCR.cpp.s:
	$(MAKE) -f CMakeFiles/evalOCR.dir/build.make CMakeFiles/evalOCR.dir/evalOCR.cpp.s
.PHONY : evalOCR.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/ANPR.dir/build.make CMakeFiles/ANPR.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/ANPR.dir/build.make CMakeFiles/ANPR.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/ANPR.dir/build.make CMakeFiles/ANPR.dir/main.cpp.s
.PHONY : main.cpp.s

trainOCR.o: trainOCR.cpp.o
.PHONY : trainOCR.o

# target to build an object file
trainOCR.cpp.o:
	$(MAKE) -f CMakeFiles/trainOCR.dir/build.make CMakeFiles/trainOCR.dir/trainOCR.cpp.o
.PHONY : trainOCR.cpp.o

trainOCR.i: trainOCR.cpp.i
.PHONY : trainOCR.i

# target to preprocess a source file
trainOCR.cpp.i:
	$(MAKE) -f CMakeFiles/trainOCR.dir/build.make CMakeFiles/trainOCR.dir/trainOCR.cpp.i
.PHONY : trainOCR.cpp.i

trainOCR.s: trainOCR.cpp.s
.PHONY : trainOCR.s

# target to generate assembly for a file
trainOCR.cpp.s:
	$(MAKE) -f CMakeFiles/trainOCR.dir/build.make CMakeFiles/trainOCR.dir/trainOCR.cpp.s
.PHONY : trainOCR.cpp.s

trainSVM.o: trainSVM.cpp.o
.PHONY : trainSVM.o

# target to build an object file
trainSVM.cpp.o:
	$(MAKE) -f CMakeFiles/trainSVM.dir/build.make CMakeFiles/trainSVM.dir/trainSVM.cpp.o
.PHONY : trainSVM.cpp.o

trainSVM.i: trainSVM.cpp.i
.PHONY : trainSVM.i

# target to preprocess a source file
trainSVM.cpp.i:
	$(MAKE) -f CMakeFiles/trainSVM.dir/build.make CMakeFiles/trainSVM.dir/trainSVM.cpp.i
.PHONY : trainSVM.cpp.i

trainSVM.s: trainSVM.cpp.s
.PHONY : trainSVM.s

# target to generate assembly for a file
trainSVM.cpp.s:
	$(MAKE) -f CMakeFiles/trainSVM.dir/build.make CMakeFiles/trainSVM.dir/trainSVM.cpp.s
.PHONY : trainSVM.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... ANPR"
	@echo "... edit_cache"
	@echo "... evalOCR"
	@echo "... rebuild_cache"
	@echo "... trainOCR"
	@echo "... trainSVM"
	@echo "... DetectRegions.o"
	@echo "... DetectRegions.i"
	@echo "... DetectRegions.s"
	@echo "... OCR.o"
	@echo "... OCR.i"
	@echo "... OCR.s"
	@echo "... Plate.o"
	@echo "... Plate.i"
	@echo "... Plate.s"
	@echo "... evalOCR.o"
	@echo "... evalOCR.i"
	@echo "... evalOCR.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... trainOCR.o"
	@echo "... trainOCR.i"
	@echo "... trainOCR.s"
	@echo "... trainSVM.o"
	@echo "... trainSVM.i"
	@echo "... trainSVM.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

